version: '3.8'

services:
  reverse-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
    command: >
      sh -c "
        apk add --no-cache openssl
        mkdir -p /etc/nginx/certs
        if [ ! -f /etc/nginx/certs/localhost.crt ]; then
          openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/certs/localhost.key -out /etc/nginx/certs/localhost.crt -subj '/CN=localhost';
        fi;
        ls /etc/nginx/certs
        nginx -g 'daemon off;'
      "
    depends_on:
      - api
      - frontend

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/app

volumes:
  postgres-data:
