version: '3.8'

services:
  reverse-proxy:
    image: nginx:alpine
    #network_mode: host
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
    command: >
      sh -c "
        apk add --no-cache openssl
        mkdir -p /etc/nginx/certs
        if [ ! -f /etc/nginx/certs/localhost.crt ]; then
          openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/certs/localhost.key -out /etc/nginx/certs/localhost.crt -subj '/CN=localhost';
        fi;
        ls /etc/nginx/certs
        nginx -g 'daemon off;'
      "
    depends_on:
      - api
      - frontend


  db:
    restart: always
    build: 
      context: ./db
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p 5432 -U myuser -d mydatabase "]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/app

