# Use the official PostgreSQL image from the Docker Hub
FROM postgres:latest

# Set environment variables for the database
#ENV POSTGRES_DB=mydatabase
#ENV POSTGRES_USER=myuser
#ENV POSTGRES_PASSWORD=mypassword

COPY init.sql /docker-entrypoint-initdb.d/

# Expose the PostgreSQL port
EXPOSE 5432
