CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Audios" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UrlKey" text NOT NULL,
    "Transcript" text NOT NULL,
    "EnglishTranslation" text NOT NULL,
    "SentenceId" text NOT NULL,
    "LanguageCode" text NOT NULL,
    "UploadedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Audios" PRIMARY KEY ("Id")
);

CREATE TABLE "Images" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UrlKey" text NOT NULL,
    "Context" text NOT NULL,
    "Description" text NOT NULL,
    "EnhancedDescription" text NOT NULL,
    "UploadedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Images" PRIMARY KEY ("Id")
);

CREATE TABLE "InteractiveStorybooks" (
    "StorybookId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "Content" text NOT NULL,
    "Language" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_InteractiveStorybooks" PRIMARY KEY ("StorybookId")
);

CREATE TABLE "Languages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Code" text NOT NULL,
    "Description" text NOT NULL,
    CONSTRAINT "PK_Languages" PRIMARY KEY ("Id")
);

CREATE TABLE "Roles" (
    "RoleId" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleName" text NOT NULL,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("RoleId")
);

CREATE TABLE "UserProfiles" (
    "UserId" uuid NOT NULL,
    "Username" text NOT NULL,
    "Email" text NOT NULL,
    "NativeLanguage" text NOT NULL,
    "TargetLanguage" text NOT NULL,
    "TargetLanguageLevel" text,
    "TargetLanguage2" text,
    "TargetLanguageLevel2" text,
    "TargetLanguage3" text,
    "TargetLanguageLevel3" text,
    "DateOfBirth" timestamp with time zone,
    "TimeZone" text,
    "UserRole" integer,
    CONSTRAINT "PK_UserProfiles" PRIMARY KEY ("UserId")
);

CREATE TABLE "StoryChoices" (
    "ChoiceId" integer GENERATED BY DEFAULT AS IDENTITY,
    "StorybookId" integer NOT NULL,
    "ChoiceText" text NOT NULL,
    "Outcome" text NOT NULL,
    CONSTRAINT "PK_StoryChoices" PRIMARY KEY ("ChoiceId"),
    CONSTRAINT "FK_StoryChoices_InteractiveStorybooks_StorybookId" FOREIGN KEY ("StorybookId") REFERENCES "InteractiveStorybooks" ("StorybookId") ON DELETE CASCADE
);

CREATE TABLE "Courses" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "Description" text NOT NULL,
    "LanguageId" integer NOT NULL,
    CONSTRAINT "PK_Courses" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Courses_Languages_LanguageId" FOREIGN KEY ("LanguageId") REFERENCES "Languages" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Badges" (
    "BadgeId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "BadgeName" text NOT NULL,
    "AwardedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Badges" PRIMARY KEY ("BadgeId"),
    CONSTRAINT "FK_Badges_UserProfiles_UserId" FOREIGN KEY ("UserId") REFERENCES "UserProfiles" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "Flashcards" (
    "FlashcardId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "Front" text NOT NULL,
    "Back" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Flashcards" PRIMARY KEY ("FlashcardId"),
    CONSTRAINT "FK_Flashcards_UserProfiles_UserId" FOREIGN KEY ("UserId") REFERENCES "UserProfiles" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "Notifications" (
    "NotificationId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Message" text NOT NULL,
    "SentAt" timestamp with time zone NOT NULL,
    "IsRead" boolean NOT NULL,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("NotificationId"),
    CONSTRAINT "FK_Notifications_UserProfiles_UserId" FOREIGN KEY ("UserId") REFERENCES "UserProfiles" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "Subscriptions" (
    "SubscriptionId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "PlanName" integer NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_Subscriptions" PRIMARY KEY ("SubscriptionId"),
    CONSTRAINT "FK_Subscriptions_UserProfiles_UserId" FOREIGN KEY ("UserId") REFERENCES "UserProfiles" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "UserGeneratedContents" (
    "ContentId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Title" text NOT NULL,
    "ContentType" integer NOT NULL,
    "Content" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_UserGeneratedContents" PRIMARY KEY ("ContentId"),
    CONSTRAINT "FK_UserGeneratedContents_UserProfiles_UserId" FOREIGN KEY ("UserId") REFERENCES "UserProfiles" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "Modules" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "Description" text NOT NULL,
    "Order" integer,
    "CourseId" integer NOT NULL,
    CONSTRAINT "PK_Modules" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Modules_Courses_CourseId" FOREIGN KEY ("CourseId") REFERENCES "Courses" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Lessons" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "ContentType" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "Order" integer,
    "ModuleId" integer NOT NULL,
    CONSTRAINT "PK_Lessons" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Lessons_Modules_ModuleId" FOREIGN KEY ("ModuleId") REFERENCES "Modules" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Progresses" (
    "ProgressId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "CourseId" integer,
    "ModuleId" integer,
    "LessonId" integer,
    "CompletionPercentage" integer NOT NULL,
    "LastUpdated" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Progresses" PRIMARY KEY ("ProgressId"),
    CONSTRAINT "FK_Progresses_Courses_CourseId" FOREIGN KEY ("CourseId") REFERENCES "Courses" ("Id"),
    CONSTRAINT "FK_Progresses_Modules_LessonId" FOREIGN KEY ("LessonId") REFERENCES "Modules" ("Id"),
    CONSTRAINT "FK_Progresses_Modules_ModuleId" FOREIGN KEY ("ModuleId") REFERENCES "Modules" ("Id"),
    CONSTRAINT "FK_Progresses_UserProfiles_UserId" FOREIGN KEY ("UserId") REFERENCES "UserProfiles" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "Questions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Text" text NOT NULL,
    "QuestionType" integer NOT NULL,
    "Answer" uuid NOT NULL,
    "Order" integer,
    "LessonId" integer NOT NULL,
    "AudioId" integer,
    "ImageId" integer,
    CONSTRAINT "PK_Questions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Questions_Audios_AudioId" FOREIGN KEY ("AudioId") REFERENCES "Audios" ("Id"),
    CONSTRAINT "FK_Questions_Images_ImageId" FOREIGN KEY ("ImageId") REFERENCES "Images" ("Id"),
    CONSTRAINT "FK_Questions_Lessons_LessonId" FOREIGN KEY ("LessonId") REFERENCES "Lessons" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Ratings" (
    "RatingId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "ContentType" integer NOT NULL,
    "ContentId" integer NOT NULL,
    "IsThumbsUp" boolean NOT NULL,
    "RatedAt" timestamp with time zone NOT NULL,
    "LessonId" integer NOT NULL,
    "ModuleId" integer,
    CONSTRAINT "PK_Ratings" PRIMARY KEY ("RatingId"),
    CONSTRAINT "FK_Ratings_Lessons_ContentId" FOREIGN KEY ("ContentId") REFERENCES "Lessons" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Ratings_Modules_ModuleId" FOREIGN KEY ("ModuleId") REFERENCES "Modules" ("Id"),
    CONSTRAINT "FK_Ratings_UserProfiles_UserId" FOREIGN KEY ("UserId") REFERENCES "UserProfiles" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "Options" (
    "Id" uuid NOT NULL,
    "Text" text NOT NULL,
    "AudioId" integer,
    "ImageId" integer,
    "QuestionId" integer NOT NULL,
    CONSTRAINT "PK_Options" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Options_Audios_AudioId" FOREIGN KEY ("AudioId") REFERENCES "Audios" ("Id"),
    CONSTRAINT "FK_Options_Images_ImageId" FOREIGN KEY ("ImageId") REFERENCES "Images" ("Id"),
    CONSTRAINT "FK_Options_Questions_QuestionId" FOREIGN KEY ("QuestionId") REFERENCES "Questions" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Badges_UserId" ON "Badges" ("UserId");

CREATE INDEX "IX_Courses_LanguageId" ON "Courses" ("LanguageId");

CREATE INDEX "IX_Flashcards_UserId" ON "Flashcards" ("UserId");

CREATE INDEX "IX_Lessons_ModuleId" ON "Lessons" ("ModuleId");

CREATE INDEX "IX_Modules_CourseId" ON "Modules" ("CourseId");

CREATE INDEX "IX_Notifications_UserId" ON "Notifications" ("UserId");

CREATE INDEX "IX_Options_AudioId" ON "Options" ("AudioId");

CREATE INDEX "IX_Options_ImageId" ON "Options" ("ImageId");

CREATE INDEX "IX_Options_QuestionId" ON "Options" ("QuestionId");

CREATE INDEX "IX_Progresses_CourseId" ON "Progresses" ("CourseId");

CREATE INDEX "IX_Progresses_LessonId" ON "Progresses" ("LessonId");

CREATE INDEX "IX_Progresses_ModuleId" ON "Progresses" ("ModuleId");

CREATE INDEX "IX_Progresses_UserId" ON "Progresses" ("UserId");

CREATE INDEX "IX_Questions_AudioId" ON "Questions" ("AudioId");

CREATE INDEX "IX_Questions_ImageId" ON "Questions" ("ImageId");

CREATE INDEX "IX_Questions_LessonId" ON "Questions" ("LessonId");

CREATE INDEX "IX_Ratings_ContentId" ON "Ratings" ("ContentId");

CREATE INDEX "IX_Ratings_ModuleId" ON "Ratings" ("ModuleId");

CREATE INDEX "IX_Ratings_UserId" ON "Ratings" ("UserId");

CREATE INDEX "IX_StoryChoices_StorybookId" ON "StoryChoices" ("StorybookId");

CREATE UNIQUE INDEX "IX_Subscriptions_UserId" ON "Subscriptions" ("UserId");

CREATE INDEX "IX_UserGeneratedContents_UserId" ON "UserGeneratedContents" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240702005243_InitialCreate', '8.0.6');

COMMIT;

-- Insert test data into tables

-- Disable foreign key checks (specific to PostgreSQL)
SET session_replication_role = replica;

-- Deleting rows from dependent tables

-- StoryChoices must be deleted before InteractiveStorybooks
DELETE FROM "StoryChoices";

-- Questions must be deleted before Lessons
DELETE FROM "Options";

-- Ratings must be deleted before Users and Lessons
DELETE FROM "Ratings";

-- Progresses must be deleted before Users, Courses, and Modules
DELETE FROM "Progresses";

-- Badges must be deleted before Users
DELETE FROM "Badges";

-- Notifications must be deleted before Users
DELETE FROM "Notifications";

-- Flashcards must be deleted before Users
DELETE FROM "Flashcards";

-- UserGeneratedContents must be deleted before Users
DELETE FROM "UserGeneratedContents";

-- Subscriptions must be deleted before Users
DELETE FROM "Subscriptions";

-- Lessons must be deleted before Modules
DELETE FROM "Lessons";

-- Modules must be deleted before Courses
DELETE FROM "Modules";

-- Courses must be deleted before Languages
DELETE FROM "Courses";

-- Audios are a dependency for Questions and Options
DELETE FROM "Audios";

-- Images are a dependency for Questions and Options
DELETE FROM "Images";

-- UserRoles must be deleted before Roles and Users
DELETE FROM "UserProfiles";

-- Main tables deletion
DELETE FROM "__EFMigrationsHistory";
DELETE FROM "InteractiveStorybooks";
DELETE FROM "Languages";
DELETE FROM "Roles";
-- Finally, delete rows from the Users table as it doesn't have dependencies anymore
DELETE FROM "UserProfiles";

-- Re-enable foreign key checks
SET session_replication_role = origin;


INSERT INTO "Languages" ("Name", "Code", "Description") VALUES
('Chinese', 'zh', 'Chinese Language'),
('Korean', 'ko', 'Korean Language'),
('English', 'en', 'English Language'),
('Japanese', 'ja', 'Japanese Language'),
('Russian', 'ru', 'Russian Language'),
('Spanish', 'es', 'Spanish Language'),
('French', 'fr', 'French Language'),
('German', 'de', 'German Language'),
('Italian', 'it', 'Italian Language'),
('Arabic', 'ar', 'Arabic Language');

-- Insert test data into the Course table
DO $$ 
DECLARE 
    row RECORD; 
BEGIN 
    FOR row IN (SELECT "Id" FROM "Languages") LOOP
        INSERT INTO "Courses" ("Title", "Description", "LanguageId") 
        VALUES ('Course 1 for ' || row."Id", 'Description 1', row."Id"),
               ('Course 2 for ' || row."Id", 'Description 2', row."Id");
    END LOOP;
END $$;

-- Insert test data into the Module table
DO $$
DECLARE row RECORD; 
BEGIN
    FOR row IN (SELECT "Id" FROM "Courses") LOOP
        INSERT INTO "Modules" ("Title", "Description", "CourseId") 
        VALUES ('Module 1 for ' || row."Id", 'Module Description 1', row."Id"),
               ('Module 2 for ' || row."Id", 'Module Description 2', row."Id");
    END LOOP;
END $$;

-- Insert test data into the Lesson table
DO $$
DECLARE row RECORD; 
BEGIN
    FOR row IN (SELECT "Id" FROM "Modules") LOOP
        INSERT INTO "Lessons" ("Title", "ContentType", "CreatedAt", "ModuleId") 
        VALUES ('Lesson 1 for ' || row."Id", 3, NOW(), row."Id"),
               ('Lesson 2 for ' || row."Id", 3, NOW(), row."Id");
    END LOOP;
END $$;

-- Insert test data into the Image table
INSERT INTO "Images" ("UrlKey", "Context", "Description", "EnhancedDescription", "UploadedAt") VALUES
('image_1.jpg', 'default', 'Image Description 1','Image Description 1', NOW()),
('image_2.jpg', 'default', 'Image Description 2','Image Description 1', NOW()),
('image_3.jpg', 'default', 'Image Description 3','Image Description 1', NOW()),
('image_4.jpg', 'default', 'Image Description 4','Image Description 1', NOW()),
('image_5.jpg', 'default', 'Image Description 5','Image Description 1', NOW()),
('image_6.jpg', 'default', 'Image Description 6','Image Description 1', NOW()),
('image_7.jpg', 'default', 'Image Description 7','Image Description 1', NOW()),
('image_8.jpg', 'default', 'Image Description 8','Image Description 1', NOW()),
('image_9.jpg', 'default', 'Image Description 9','Image Description 1', NOW()),
('image_10.jpg', 'default', 'Image Description 10','Image Description 1', NOW());

-- Insert test data into the Audio table
INSERT INTO "Audios" ("UrlKey", "Transcript", "EnglishTranslation", "SentenceId", "LanguageCode", "UploadedAt") VALUES
('audio_1.mp3', 'Transcript 1', 'Translation 1', '1', (SELECT "Code" FROM "Languages" WHERE "Name"='Chinese'), NOW()),
('audio_2.mp3', 'Transcript 2', 'Translation 2', '2', (SELECT "Code" FROM "Languages" WHERE "Name"='Korean'), NOW()),
('audio_3.mp3', 'Transcript 3', 'Translation 3', '3', (SELECT "Code" FROM "Languages" WHERE "Name"='English'), NOW()),
('audio_4.mp3', 'Transcript 4', 'Translation 4', '4', (SELECT "Code" FROM "Languages" WHERE "Name"='Japanese'), NOW()),
('audio_5.mp3', 'Transcript 5', 'Translation 5', '5', (SELECT "Code" FROM "Languages" WHERE "Name"='Russian'), NOW()),
('audio_6.mp3', 'Transcript 6', 'Translation 6', '6', (SELECT "Code" FROM "Languages" WHERE "Name"='Spanish'), NOW()),
('audio_7.mp3', 'Transcript 7', 'Translation 7', '7', (SELECT "Code" FROM "Languages" WHERE "Name"='French'), NOW()),
('audio_8.mp3', 'Transcript 8', 'Translation 8', '8', (SELECT "Code" FROM "Languages" WHERE "Name"='German'), NOW()),
('audio_9.mp3', 'Transcript 9', 'Translation 9', '9', (SELECT "Code" FROM "Languages" WHERE "Name"='Italian'), NOW()),
('audio_10.mp3', 'Transcript 10', 'Translation 10', '10', (SELECT "Code" FROM "Languages" WHERE "Name"='Arabic'), NOW());

-- Insert test data into the Question table
DO $$
DECLARE row RECORD; 
BEGIN
    FOR row IN (SELECT "Id" FROM "Lessons" LIMIT 10) LOOP
        INSERT INTO "Questions" ("Text", "QuestionType", "Answer", "LessonId", "AudioId", "ImageId") 
        VALUES ('Question 1 for ' || row."Id", 6, gen_random_uuid(), row."Id", (SELECT "Id" FROM "Audios" WHERE "UrlKey"='audio_1.mp3'), (SELECT "Id" FROM "Images" WHERE "UrlKey"='image_1.jpg')),
               ('Question 2 for ' || row."Id", 6, gen_random_uuid(), row."Id", (SELECT "Id" FROM "Audios" WHERE "UrlKey"='audio_2.mp3'), (SELECT "Id" FROM "Images" WHERE "UrlKey"='image_2.jpg')),
               ('Question 3 for ' || row."Id", 6, gen_random_uuid(), row."Id", (SELECT "Id" FROM "Audios" WHERE "UrlKey"='audio_3.mp3'), (SELECT "Id" FROM "Images" WHERE "UrlKey"='image_3.jpg')),
               ('Question 4 for ' || row."Id", 6, gen_random_uuid(), row."Id", (SELECT "Id" FROM "Audios" WHERE "UrlKey"='audio_4.mp3'), (SELECT "Id" FROM "Images" WHERE "UrlKey"='image_4.jpg')),
               ('Question 5 for ' || row."Id", 6, gen_random_uuid(), row."Id", (SELECT "Id" FROM "Audios" WHERE "UrlKey"='audio_5.mp3'), (SELECT "Id" FROM "Images" WHERE "UrlKey"='image_5.jpg')),
               ('Question 6 for ' || row."Id", 6, gen_random_uuid(), row."Id", (SELECT "Id" FROM "Audios" WHERE "UrlKey"='audio_6.mp3'), (SELECT "Id" FROM "Images" WHERE "UrlKey"='image_6.jpg')),
               ('Question 7 for ' || row."Id", 6, gen_random_uuid(), row."Id", (SELECT "Id" FROM "Audios" WHERE "UrlKey"='audio_7.mp3'), (SELECT "Id" FROM "Images" WHERE "UrlKey"='image_7.jpg')),
               ('Question 8 for ' || row."Id", 6, gen_random_uuid(), row."Id", (SELECT "Id" FROM "Audios" WHERE "UrlKey"='audio_8.mp3'), (SELECT "Id" FROM "Images" WHERE "UrlKey"='image_8.jpg')),
               ('Question 9 for ' || row."Id", 6, gen_random_uuid(), row."Id", (SELECT "Id" FROM "Audios" WHERE "UrlKey"='audio_9.mp3'), (SELECT "Id" FROM "Images" WHERE "UrlKey"='image_9.jpg')),
               ('Question 10 for ' || row."Id", 6, gen_random_uuid(), row."Id",(SELECT "Id" FROM "Audios" WHERE "UrlKey"='audio_10.mp3'), (SELECT "Id" FROM "Images" WHERE "UrlKey"='image_10.jpg'));
    END LOOP;
END $$;


-- Insert test data into the Option table
DO $$
DECLARE row RECORD; 
BEGIN
    FOR row IN (SELECT "Id" FROM "Questions") LOOP
        INSERT INTO "Options" ("Id", "Text", "AudioId", "ImageId", "QuestionId") 
        VALUES (gen_random_uuid(), 'Option 1 for ' || row."Id", (SELECT "Id" FROM "Audios" WHERE "UrlKey"='audio_1.mp3'), (SELECT "Id" FROM "Images" WHERE "UrlKey"='image_1.jpg'), row."Id"),
               (gen_random_uuid(), 'Option 2 for ' || row."Id", (SELECT "Id" FROM "Audios" WHERE "UrlKey"='audio_2.mp3'), (SELECT "Id" FROM "Images" WHERE "UrlKey"='image_2.jpg'), row."Id"),
               (gen_random_uuid(), 'Option 3 for ' || row."Id", (SELECT "Id" FROM "Audios" WHERE "UrlKey"='audio_3.mp3'), (SELECT "Id" FROM "Images" WHERE "UrlKey"='image_3.jpg'), row."Id"),
               (gen_random_uuid(), 'Option 4 for ' || row."Id", (SELECT "Id" FROM "Audios" WHERE "UrlKey"='audio_4.mp3'), (SELECT "Id" FROM "Images" WHERE "UrlKey"='image_4.jpg'), row."Id");
    END LOOP;
END $$;

-- Drop the temporary table if it already exists
DROP TABLE IF EXISTS temp_users;

-- Create a temporary table with GUID and email
CREATE TEMPORARY TABLE temp_users (
    id uuid,
    email text
);

DELETE FROM temp_users;

-- Insert 2 rows of data into the temporary table
INSERT INTO temp_users (id, email) VALUES 
('f4d82458-40e1-7008-40e2-cd45634a3da8', 'e@gmail.com'),
('4438e4d8-0051-706a-e62e-caf930ebf153', '7@gmail.com');


-- Insert test data into the InteractiveStorybooks table
INSERT INTO "InteractiveStorybooks" ("Title", "Content", "Language", "CreatedAt") VALUES
('Storybook 1', 'Content 1', 'English', NOW()),
('Storybook 2', 'Content 2', 'Spanish', NOW()),
('Storybook 3', 'Content 3', 'Korean', NOW());

-- Insert test data into the StoryChoices table
INSERT INTO "StoryChoices" ("StorybookId", "ChoiceText", "Outcome") VALUES
((SELECT "StorybookId" FROM "InteractiveStorybooks" WHERE "Title"='Storybook 1'), 'Choice 1', 'Outcome 1'),
((SELECT "StorybookId" FROM "InteractiveStorybooks" WHERE "Title"='Storybook 2'), 'Choice 2', 'Outcome 2'),
((SELECT "StorybookId" FROM "InteractiveStorybooks" WHERE "Title"='Storybook 3'), 'Choice 3', 'Outcome 3');


-- Variables for GUID and email for UserProfiles
DO $$
DECLARE
    user_record RECORD;
    i int := 1;
BEGIN
    FOR user_record IN (SELECT * FROM temp_users) LOOP
        INSERT INTO "UserProfiles" ("UserId", "Username", "Email", "NativeLanguage", "TargetLanguage", "TargetLanguageLevel", "DateOfBirth", "TimeZone", "UserRole") 
        VALUES (user_record.id, 'user' || i, user_record.email, 'English', 'Spanish', 'Beginner', '2000-01-01', 'UTC', 0);

        -- Add test data into the Badge table
        INSERT INTO "Badges" ("UserId", "BadgeName", "AwardedAt") 
        VALUES (user_record.id, 'Badge ' || i, NOW());

        -- Add test data into the Flashcard table
        INSERT INTO "Flashcards" ("UserId", "Front", "Back", "CreatedAt") 
        VALUES (user_record.id, 'Front ' || i, 'Back ' || i, NOW());

        -- Add test data into the Progress table
        INSERT INTO "Progresses" ("UserId", "CourseId", "ModuleId", "CompletionPercentage", "LastUpdated") 
        VALUES (user_record.id, 
                (SELECT "Id" FROM "Courses" LIMIT 1 OFFSET i-1), 
                (SELECT "Id" FROM "Modules" LIMIT 1 OFFSET i-1),
                i*10, 
                NOW());
        
        i := i + 1;
    END LOOP;
END $$;